/**
 * Generated by .github/workflows/new-archivesspace-release.yml
 */
export const LATEST_AS_RELEASE = {
  tagName: 'v4.2.0',
  htmlUrl: 'https://github.com/archivesspace/archivesspace/releases/tag/v4.2.0',
} as const
