FROM node:22
WORKDIR /app
RUN apt-get update && apt-get install -y \
  libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 \
  libdrm2 libgbm1 libxkbcommon0 libxcb-randr0 \
  xvfb \
  build-essential git curl ca-certificates --no-install-recommends && \
  rm -rf /var/lib/apt/lists/*
COPY package*.json ./
RUN npm install
COPY . .
CMD ["sh", "-c", "npm run test:server"]