name: Lint and format checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  stylelint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm ci

      - name: Run Stylelint
        run: npm run stylelint:check

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run prettier:check
